#%RAML 1.0
types:
  getDataTypeUsers:
    items:
      properties:
        id:
          example: 2482
          type: number
          format: int
        name:
          example: Kartik Kocchar
          type: string
        gender:
          example: female
          type: string
        status:
          example: inactive
          type: string
title: IE-Major-Asg-Abdul Aabid Khan
mediaType:
  - application/json
protocols:
  - HTTP
/milestone1:
  get:
    responses:
      "200":
        body:
          type: getDataTypeUsers
          items:
            type: object
